export { default as LandingPage } from './LandingPage'
export { default as ViewPost } from './ViewPost'
export { default as NotFound } from './NotFound'
export { default as Login } from './Login'
export { default as Signup } from './Signup'
